version: 0.0
os: linux
files:
- source: /
  destination: /home/ubuntu/mean-yeti
hooks:
  ApplicationStop:
    - location: /home/ubuntu/mean-yeti/bin/app-stop
      timeout: 10
      runas: ubuntu
  AfterInstall:
    - location: /home/ubuntu/mean-yeti/bin/install-pkgs
      timeout: 1200
      runas: ubuntu
  ApplicationStart:
    - location: /home/ubuntu/mean-yeti/bin/app-start
      timeout: 60
      runas: ubuntu
  ValidateService:
    - location: /home/ubuntu/mean-yeti/bin/app-validate
      timeout: 10
      runas: ubuntu