version: 0.0
os: linux
files:
- source: /
  destination: /home/ubuntu/mean-yeti
hooks:
  AfterInstall:
    - location: bin/install-pkgs
      timeout: 1200
      runas: root
  ApplicationStart:
    - location: bin/app-start
      timeout: 60
      runas: ubuntu