version: 0.0
os: linux
files:
- source: /
 destination: /home/ubuntu/mean-yeti

permissions:
- object: /
   pattern: "**"
   owner: ubuntu
   group: ubuntu

hooks:
ApplicationStop:
   - location: bin/app-stop
     timeout: 10
     runas: ubuntu

AfterInstall:
   - location: bin/install-pkgs
     timeout: 1200
     runas: ubuntu

ApplicationStart:
   - location: bin/app-start
     timeout: 60
     runas: ubuntu

ValidateService:
   - location: bin/app-validate
     timeout: 10
     runas: ubuntu
